[package]
name = "neuralink_final"
version = "0.1.0"
edition = "2021"

[dependencies]
approx = "0.5.1"
nalgebra = "0.33.2"
rand = "0.8.5"
roots = "0.0.8"
tokio = { version = "1", features = ["full"] }

